### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ARosca19** [p-r-m-n/esp32-61850-socket#3]
Hello, now I have another error.

CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error in CMakeLists.txt:
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.

CMake Error in CMakeLists.txt:
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.24)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

The error comes from CMakeError.log, it doesn't appear the paths to the compilers C and CXX. I wrote the oath in the PowerShell but I don't know what to do next. Can you help me?

this error comes from this path: examples->build->log->idf_py_stderr_output_18528

**Comment by p-r-m-n** [comment]
The right project folder is opened in vscode? if so, you can build by pressing this button in the picture
![image](https://github.com/p-r-m-n/esp32-61850-socket/assets/92051410/40376c2c-0889-4115-b0e1-251cecdf5879)

**Comment by ARosca19** [comment]
In which folder I have to be? I wrote in terminal from the tcp/.../pub folder, it is not the right one?

**Comment by p-r-m-n** [comment]
> In which folder I have to be? I wrote in terminal from the tcp/.../pub folder, it is not the right one?

yes, you can try from terminal. but, i don't know if the terminal command you used is the right one. you can compare your command and its options with the build task associated with the button in the picture, in the file "tasks.json" inside the folder ".vscode" in the project directory.

the right folder for each project is the top folder, "tcp_socket_61850_pub" or "tcp_socket_61850_sub".

**Comment by ARosca19** [comment]
Ok, thank you but I don't have the tasks.json in the.vscode folder I only have these 2 jsons: c_cpp_properties.json and settings.json.

**Comment by p-r-m-n** [comment]
> Ok, thank you but I don't have the tasks.json in the.vscode folder I only have these 2 jsons: c_cpp_properties.json and settings.json.

have you configured the esp idf through the esp idf extension in vscode? if not, press F1 inside vscode and then choose "ESP-IDF: Configure ESP-IDF extension", as the image shows:
![image](https://github.com/p-r-m-n/esp32-61850-socket/assets/92051410/cded5f02-298d-4390-bc23-23380f6a74f3)

**Comment by ARosca19** [comment]
So I have to open the project with the extension ESP-IDF?

**Comment by p-r-m-n** [comment]
> So I have to open the project with the extension ESP-IDF?

The esp-idf extension should be enabled and configured with your ESP-IDF for this project.

**Comment by ARosca19** [comment]
So if I want to use your project I have to only install the extension Esp-Idf and to open your project from the github in the esp-idf extension? And another question, when I press the button to configure the esp-idf extension I have to open the project in the extins? The steps: import project-> choose folder etc?

**Comment by p-r-m-n** [comment]
> So if I want to use your project I have to only install the extension Esp-Idf and to open your project from the github in the esp-idf extension? And another question, when I press the button to configure the esp-idf extension I have to open the project in the extins? The steps: import project-> choose folder etc?

no, the "configure extension" part is needed only to associate the ESP-IDF you use (my version is 5.1.2) with vscode, so that vscode will be able to execute any tasks (like build) using ESP-IDF. The project can be used after the extension is properly configured.

to open the project after the configuration you can simply open its folder. I'm not acquainted with the "import project" option.

**Comment by teocarla** [comment]
Is it necessary to download the library "They both use a modified version of libiec61850 (https://github.com/mz-automation/libiec61850), which is necessary to create a hardware abstraction layer (HAL) for the esp32. All credits should be given to the respective authors."Or is the library in the broiect enough?

**Comment by p-r-m-n** [comment]
> Is it necessary to download the library "They both use a modified version of libiec61850 (https://github.com/mz-automation/libiec61850), which is necessary to create a hardware abstraction layer (HAL) for the esp32. All credits should be given to the respective authors."Or is the library in the broiect enough?

each project folder already contains a modified version of the library, you don't have to download it.

**Comment by teocarla** [comment]
You put “esp32-61850-socket-main” folder in the C:\Espressif\frameworks\esp-idf-v5.1.2? Or it doesn't matter?

**Comment by p-r-m-n** [comment]
> You put “esp32-61850-socket-main” folder in the C:\Espressif\frameworks\esp-idf-v5.1.2? Or it doesn't matter?

no, the project should be located outside the ESP-IDF folder. It's not recommended to make changes to the ESP-IDF folder, unless you know what you're doing. “esp32-61850-socket-main” is a folder which contains two projects, each one can be opened in vscode.

**Comment by teocarla** [comment]
![image](https://github.com/p-r-m-n/esp32-61850-socket/assets/170935689/db9272af-d408-4622-9e69-dda8599be4b8)
![Screenshot 2024-06-11 192520](https://github.com/p-r-m-n/esp32-61850-socket/assets/170935689/9bfae890-a8dc-4c08-a69b-f5137f36c3c7)
I have this error for both terminals, on both boards although it shows Build successfully.
Do you have any idea how to fix it? Or does it work even if it shows up like this?

**Comment by p-r-m-n** [comment]
> ![image](https://private-user-images.githubusercontent.com/170935689/338669142-db9272af-d408-4622-9e69-dda8599be4b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMjQwMjUsIm5iZiI6MTcxODEyMzcyNSwicGF0aCI6Ii8xNzA5MzU2ODkvMzM4NjY5MTQyLWRiOTI3MmFmLWQ0MDgtNDYyMi05ZTY5LWRkYTg1OTliZTRiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQxNjM1MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDJjNGQwN2RiNjg2MzA4MGExOGJlODhkMDcyZjlhNzQxNDRmMzk5NTY3MzBkODNmMTA1ZWQ5YWQwZGJhY2MxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.b2K7OEa55UMQyYr3wWZwkH4FiQf0fPaUND1-G3fJc7o) ![Screenshot 2024-06-11 192520](https://private-user-images.githubusercontent.com/170935689/338669231-9bfae890-a8dc-4c08-a69b-f5137f36c3c7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMjQwMjUsIm5iZiI6MTcxODEyMzcyNSwicGF0aCI6Ii8xNzA5MzU2ODkvMzM4NjY5MjMxLTliZmFlODkwLWE4ZGMtNGMwOC1hNjliLWY1MTM3ZjM2YzNjNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQxNjM1MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjY4YzAwMjFkNzVmNTRmMTgyNzM0NzUwZTc0NzU5MGVhYjBlM2ViN2IwMjIxNWM4MTAyNGZkNGM0NWQwZjdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5kbMCcIowdqAEoiFHDH-VqvwtYY8Ydv70-724IIEenc) I have this error for both terminals, on both boards although it shows Build successfully. Do you have any idea how to fix it? Or does it work even if it shows up like this?

the build part only creates the image that will be flashed to the esp. after the build, you have to flash image to your esp board by selecting a com port (you have com ports 4 and 6 free to use). After successful flashing, you should restart the board and it will be ready to monitor.

if you dont have access to monitor the com port, it is probably in use by another program. also, you can disable the "cmake tools" extension in the project workplace, since it is not necessary.

**Comment by teocarla** [comment]
After putting the code on each esp32, how did you connect them together? What did you use to see their screen?

**Comment by p-r-m-n** [comment]
> After putting the code on each esp32, how did you connect them together? What did you use to see their screen?

they should be on the same ethernet LAN, so, connect both esp32's to a switch/router using a ethernet cable.

The IEC-61850 standard requires the use of a VLAN MAC address that you also need to configure on your switch/router. If you want to use VLAN, you can configure the GOOSE destination MAC address in the publisher ("tcp_socket_61850_pub") main source code (the stack_config.h of libiec61850 has a defined standard VLAN MAC address for GOOSE). You should also configure the destination MAC address in the main code of the subscriber ("tcp_socket_61850_sub").

If you don't want to use a VLAN, you can simply use the ethernet MAC address of the subscriber esp32 as i did in my code. The communication will still work, but won't abide by the standard.

To see that both esp32's successfully created an IED, you can use softwares like IEDSCOUT or ied_explorer to connect using the MMS protocol and see its variables. you can also monitor the esp32's through serial port. To see the GOOSE communication, you can use wireshark (if using VLAN) or you can simply modify the goose listener function on the esp32 subscriber to print some text when a GOOSE event occurs. The code is currently sending and receiving one float value from one esp to another through GOOSE.

**Comment by p-r-m-n** [comment]
i'm assuming this issue was solved. Just comment below and i can reopen if any problem persists.
